# Generated by Django 5.2 on 2025-05-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UMLDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diagram_type', models.CharField(choices=[('class', 'Class Diagram'), ('usecase', 'Use Case Diagram')], max_length=20)),
                ('image', models.ImageField(upload_to='uml/')),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
    ]
